### PR TITLE
Upgrading Tokio for 0.2.0, adding examples with actix and actix-web

### PR DESCRIPTION
**Pull request by dangerousplay**
- Removing old examples.

### CODE REVIEW

**Comment by Rufflewind** [comment]
Thanks for the PR!  It seems `tokio` has [native support for files](https://docs.rs/tokio/0.2.9/tokio/fs/struct.File.html) nowadays.  Is there still a use case for this library?

**Comment by WGH-** [comment]
Yes, `tokio::fs::File` doesn't seem to handle `EAGAIN`, so reading such file returns a `WouldBlock` error instead of proper "blocking" through the event loop.

**Comment by Rufflewind** [comment]
> Yes, `tokio::fs::File` doesn't seem to handle `EAGAIN`, so reading such file returns a `WouldBlock` error instead of proper "blocking" through the event loop.

Could this issue be resolved upstream?

**Comment by WGH-** [comment]
In theory yes. However, given that the issue essentially asking for this is stalled, it's not clear whether they want to include it in the main crate: https://github.com/tokio-rs/tokio/issues/2558

As an example from another language, Go runtime automatically detects that the file is non-blocking and uses the runtime poller: https://github.com/golang/go/commit/ea5825b0b64e1a017a76eac0ad734e11ff557c8e

**Comment by Rufflewind** [comment]
Thanks for the pull request!

**Comment by WGH-** [comment]
FWIW, tokio 0.3 has `tokio::io::unix::AsyncFd`, which looks like direct replacement.

**Pull request merged**
