### PR TITLE
Update to tokio

### PR DESCRIPTION
**Pull request by asonix**

### CODE REVIEW

**Comment by asonix** [comment]
fixes https://github.com/Rufflewind/tokio-file-unix/issues/8

**Comment by Rufflewind** [comment]
Thank you for the pull request!  I really appreciate your work on fixing #8.

Unfortunately, most of the refactoring needed for #8 had already been done yesterday on the [dev](https://github.com/Rufflewind/tokio-file-unix/tree/dev) branch (with the difference that the `Handle` arguments will stay).  Please give that branch a try and let me know what you think!

**Comment by asonix** [comment]
Alright, so you solved the `StdIn::lock()` problem by just not locking stdin. Looking at the examples, I was really confused about how you were able to use `tokio::run()`, but now I understand.

**Comment by asonix** [comment]
I'm going to go ahead and close this, since I prefer your implementation to mine

**Pull request closed without merging**
